### ISSUE TITLE
impulse response is missing an input?

### ISSUE THREAD

**Issue by floswald** [justinenayral/ACE_Traeger_replication.jl#4]
```
julia> ACE_Traeger_replication.Impulse_response_combined()
ERROR: File "/Users/floswald/git/Comp2024/ACE_Traeger_replication.jl/impulse_timestep_5_logi_001.mat" does not exist and create was not specified
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] matopen(filename::String, rd::Bool, wr::Bool, cr::Bool, tr::Bool, ff::Bool, compress::Bool)
   @ MAT ~/.julia/packages/MAT/K2D15/src/MAT.jl:45
 [3] matopen(fname::String, mode::String; compress::Bool)
   @ MAT ~/.julia/packages/MAT/K2D15/src/MAT.jl:88
 [4] matopen
   @ ~/.julia/packages/MAT/K2D15/src/MAT.jl:87 [inlined]
 [5] matopen
   @ ~/.julia/packages/MAT/K2D15/src/MAT.jl:97 [inlined]
 [6] matread(filename::String)
   @ MAT ~/.julia/packages/MAT/K2D15/src/
```

**Comment by norbertmonti** [comment]
Please make sure that you have all of the following .mat datasets downloaded from the replication package of the paper, and that you saved them in your "datapath" folder of choice:

    impulse_timestep_5_logi_001.mat
    impulse_timestep_1_logi_001.mat
    Venmans_CS3_lam_1p06.mat
    Impulse_Response_Bern2p5_Joos.mat
    Impulse_Response_Bern2p5_PD_Joos.mat
    Venmans_CS3p1.mat

Please do let us know if you still run into issues once this has been checked or if you have further questions!

**Comment by floswald** [comment]
ok but then in your _package installation guide_ you cannot have point 4 "run the module". you have to get the data before that point.

**Comment by norbertmonti** [comment]
The installation guide includes instructions on downloading the data:

![installation_guide](https://github.com/justinenayral/ACE_Traeger_replication.jl/assets/124732471/62f41f52-04c3-424a-a0b3-5f9b48f5ac69)

**Comment by floswald** [comment]
sure. but you arrive to step 4 here and you fail. you need to put the data downloading before step 4. 
<img width="980" alt="Screenshot 2024-05-23 at 10 00 34" src="https://github.com/justinenayral/ACE_Traeger_replication.jl/assets/1021558/079618f1-f3db-48b8-bc2c-a376fb1bf220">

**Comment by norbertmonti** [comment]
By using include("ACE_Traeger_replication.jl") you don't actually run the functions, so it will still work without the data. Please do try, and let us know if it fails. Happy to change the structure of instructions otherwise.
